# Generated by Django 3.0.7 on 2020-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200614_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='adderss',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
